name: Release Application

on:
    push:
        tags:
            - "v*"
    workflow_dispatch:
        inputs:
            version:
                description: "Version à publier (ex: 1.0.1)"
                required: true
                default: "1.0.1"

jobs:
    release:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [windows-latest, macos-latest, ubuntu-latest]

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "18"
                  cache: "npm"

            - name: Install dependencies
              run: npm ci

            - name: Build and release
              env:
                  GH_TOKEN: ${{ secrets.TOKEN }}
                  # Pour repository privé, utiliser un token personnel
                  # Ajouter GITHUB_PERSONAL_TOKEN dans les secrets du repository
                  GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN || secrets.TOKEN }}
              run: npm run build-publish

            - name: Upload release artifacts
              uses: actions/upload-artifact@v3
              with:
                  name: release-${{ matrix.os }}
                  path: dist/
                  retention-days: 30
